### ISSUE TITLE
Local DOM styling

### ISSUE THREAD

**Issue by jdaroesti** [safetychanger/iron-swiper#9]
The recommended way to style a Polymer 1.0 element is with css variables. This allows other users to freely style the element. 

https://www.polymer-project.org/1.0/docs/devguide/styling

Without variables it is difficult to update and remove styles of the carousel. The only way is to use the deprecated `/deep/` combinator. i.e:

```css
.swiper /deep/ .swiper-slide {
     background-color: red;
}
```

For example, after variables, some css rules would look like this:
```css
.swiper-slide {
  background-color: var(--primary-background-color);

  ... other rules
}
```

The styling problem is only present when using native shadow DOM (without polyfills, like `webcomponents.js`).
